Fix linting issues
Using [shellcheck](https://github.com/koalaman/shellcheck) to perform
static code analysis. Many of the changes are to protect against word
splitting, fragile code chunks, and unused code among others. Removed
whitespace from the end of lines, converts all tabs to spaces, and adds
the `#!/bin/bash` chant to each script.

`babun-core/plugins/pact/src/pact` still has a few instances of issue [SC2002](https://github.com/koalaman/shellcheck/wiki/SC2002).

diff --git a/babun-core/plugins/core/src/babun b/babun-core/plugins/core/src/babun
--- a/babun-core/plugins/core/src/babun
+++ b/babun-core/plugins/core/src/babun
@@ -1,9 +1,15 @@
 #!/bin/bash
 set -e -f -o pipefail
 source "/usr/local/etc/babun.instance"
+# shellcheck source=/usr/local/etc/babun/source/babun-core/tools/script.sh
 source "$babun_tools/script.sh"
+# shellcheck source=/usr/local/etc/babun/source/babun-core/tools/procps.sh
 source "$babun_tools/procps.sh"
+# shellcheck source=/usr/local/etc/babun/source/babun-core/tools/check.sh
 source "$babun_tools/check.sh"
+
+# babun
+core="$babun_source/babun-core"
 
 check_only_one_running "babun"
 
@@ -56,89 +62,37 @@ function welcome()
   echo -e "This project is created and maintained by Tom Bujok (@tombujok) and Lukasz Pielak (@lukaszpielak)."
 }
 
-#babun
-core="/usr/local/etc/babun/source/babun-core"
-
-# process options
-noscripts=0
-update=0
-file=""
-command=""
-args=""
-
-while test $# -gt 0
-do
-  case "$1" in
-
-    --help)
-      usage
-      exit 0
-    ;;
-
-    --version)
-      version
-      exit 0
-    ;;
-
-    --welcome)
-      welcome
-      exit 0
-    ;;
-
-    --login)
-      login
-      exit 0
-    ;;
-
-    update|check|shell|install|login)
-      if test "-$command-" = "--"
-      then
-        command=$1
-      fi
-      shift
-
-    ;;
-
-    *)
-      if [[ $args == "" ]]; then
-        args="$1";
-      else
-        args="$args $1";
-      fi
-      shift
-    ;;
-
-  esac
-done
-
-
 function update()
 {
-  if [ "$args" != "" ] && [ "$args" != "--force" ]; then echo "ERROR: Wrong argument $args"; exit 1; fi
-  echo "Executing babun update"
+    local args="$1"
 
-  permcheck=$( chmod 777 /usr/local/bin/babun 2> /dev/null || echo "FAILED" )
-  if [[  $permcheck == "FAILED" ]]; then
-    echo -e "ERROR: You don't have write permission to / filesystem. Aborting!"
-    echo -e "Have you installed babun as admin and run it from a non-admin account? Retry as admin."
-    exit 1
-  fi
+    if [ "$args" != "" ] && [ "$args" != "--force" ]; then echo "ERROR: Wrong argument $args"; exit 1; fi
+    echo "Executing babun update"
 
-  cp "$core"/tools/update_source.sh /tmp/update_source.sh
-  /tmp/update_source.sh "$args"
-  exit 0
+    permcheck=$( chmod 777 /usr/local/bin/babun 2> /dev/null || echo "FAILED" )
+    if [[  $permcheck == "FAILED" ]]; then
+        echo -e "ERROR: You don't have write permission to / filesystem. Aborting!"
+        echo -e "Have you installed babun as admin and run it from a non-admin account? Retry as admin."
+        exit 1
+    fi
+
+    cp "$core"/tools/update_source.sh /tmp/update_source.sh
+    /tmp/update_source.sh "$args"
+    exit 0
 }
 
 function install()
 {
-  if ! [[ $args == "" ]]; then echo "ERROR: Wrong argument $args"; exit 1; fi
-  echo "Executing babun install"
-  "$core"/plugins/install_home.sh
-  exit 0
+    local args="$1"
+    if ! [[ $args == "" ]]; then echo "ERROR: Wrong argument $args"; exit 1; fi
+    echo "Executing babun install"
+    "$core"/plugins/install_home.sh
+    exit 0
 }
 
 function check()
 {
+    local args="$1"
     if ! [[ $args == "" ]]; then echo "ERROR: Wrong argument $args"; exit 1; fi
     echo "Executing babun check"
     babun_check
@@ -146,74 +100,82 @@ function check()
 
 function shell()
 {
+    newshell="$1"
     passwd=$( sort -u /etc/passwd )
     if ! [[ -z "$passwd" ]]; then
         echo "$passwd" > /etc/passwd
     fi
-    newshell=$args
     currshell=$( awk "/^$USERNAME/ { print $1 }" /etc/passwd | grep -oh ":/.*sh" | grep -oP "(?<=.:)/.*" )
+
     if [[ $newshell == "" ]]; then
         echo "$currshell"
-    else
-        if ! [ -f $newshell ]; then
-           echo "ERROR: Cannot set shell to $newshell. Specified shell does not exist!"
-           exit 1
-        fi
-        echo "$currshell"
-        echo "$newshell"
-        sed -i "/^$USERNAME/s|$currshell|$newshell|" "/etc/passwd" || "ERROR: Changing shell to $newshell failed"
+        exit 0
     fi
+
+    if ! [ -f "$newshell" ]; then
+       echo "ERROR: Cannot set shell to $newshell. Specified shell does not exist!"
+       exit 1
+    fi
+
+    echo "$currshell"
+    echo "$newshell"
+    sed -i "/^$USERNAME/s|$currshell|$newshell|" "/etc/passwd" || echo "ERROR: Changing shell to $newshell failed" ; exit 1
 }
 
-function login()
-{
-    proc_shell_login
-}
-
-case "$command" in
-
-  update)
-
-    update
-  ;;
-
-
-  check)
-
-    check
-  ;;
-
-  shell)
-
-    shell
-  ;;
-
-  install)
-
-    install
-  ;;
-
-  login)
-
-    login
-  ;;
-
-  *)
-
-    # forward the execution to the plugin in the babun <plugin_name> cmd format
-    cmds=($args)
-    cmdsLength=${#cmds[@]}
-    if [ $cmdsLength -gt 0 ]; then
-      if [[ -f "$babun_plugins/${cmds[0]}/exec.sh" ]]; then
-        "$babun_plugins/${cmds[0]}/exec.sh" ${cmds[@]:1}
-      else
-        usage
-      fi
-    else
-      usage
-    fi
-  ;;
-
+# Main processing of inputs
+case $# in
+  0) usage ; exit 0 ;;
 esac
 
+case $1 in
+    --help)
+        usage
+        exit 0
+        ;;
 
+    --version)
+        version
+        exit 0
+        ;;
+
+    --welcome)
+        welcome
+        exit 0
+        ;;
+
+    --login|login)
+        # shellcheck disable=SC2119
+        proc_shell_login
+        exit 0
+        ;;
+
+    check)
+        shift; check "$@" ;;
+
+    install)
+        shift; install "$@" ;;
+
+    update)
+        shift; update "$@" ;;
+
+    shell)
+        shift; shell "$@" ;;
+
+    *)
+        # forward the execution to the plugin in the babun <plugin_name> cmd format
+        # the first input parameter should be the plugin name and the remainder are
+        # inputs to the plugin exec script.
+        plugin="$1"
+        shift
+        if [ $# -gt 0 ]; then
+            if [[ -f "$babun_plugins/$plugin/exec.sh" ]]; then
+                "$babun_plugins/$plugin/exec.sh" "$@"
+            else
+                usage
+            fi
+        else
+            usage
+        fi
+
+        ;;
+esac
diff --git a/babun-core/plugins/pact/src/pact b/babun-core/plugins/pact/src/pact
--- a/babun-core/plugins/pact/src/pact
+++ b/babun-core/plugins/pact/src/pact
@@ -4,17 +4,19 @@ set -f -o pipefail
 # set -e
 
 source "/usr/local/etc/babun.instance"
-# source "$babun_tools/script.sh"
+# shellcheck source=/usr/local/etc/babun/source/babun-core/tools/check.sh
 source "$babun_tools/check.sh"
+# shellcheck source=/usr/local/etc/babun/source/babun-core/tools/procps.sh
 source "$babun_tools/procps.sh"
+# shellcheck source=/home/tester/.pact/pact.repo
 source ~/.pact/pact.repo
 
 # this script requires some packages
-WGET=`which wget 2> /dev/null`
-BZIP2=`which bzip2 2> /dev/null`
-TAR=`which tar 2> /dev/null`
-GAWK=`which awk 2> /dev/null`
-XZ=`which xz 2> /dev/null`
+WGET=$(which wget 2> /dev/null)
+BZIP2=$(which bzip2 2> /dev/null)
+TAR=$(which tar 2> /dev/null)
+GAWK=$(which awk 2> /dev/null)
+XZ=$(which xz 2> /dev/null)
 if test "-$WGET-" = "--" || test "-$BZIP2-" = "--" || test "-$TAR-" = "--" \
   || test "-$GAWK-" = "--" || test "-$XZ-" = "--"
 then
@@ -62,52 +64,51 @@ function findworkspace()
 {
   # default working directory and mirror
 
-  mirror=$PACT_REPO
-  if [[ -z $mirror ]]; then
-  echo "WARNINIG! ~/.pact/pact.repo does not contains \$PACT_REPO mirror address. Using the default one!"
-  mirror=http://mirrors.kernel.org/sourceware/cygwin/
-  fi
-  cache=/setup
+    mirror=$PACT_REPO
+    if [[ -z $mirror ]]; then
+        echo "WARNINIG! ~/.pact/pact.repo does not contains $PACT_REPO mirror address. Using the default one!"
+        mirror=http://mirrors.kernel.org/sourceware/cygwin/
+    fi
+    cache=/setup
 
-  # work wherever setup worked last, if possible
-  mirrordir="`echo "$mirror" | sed -e "s/:/%3a/g" -e "s:/:%2f:g"`"
+    # work wherever setup worked last, if possible
+    mirrordir="$(echo "$mirror" | sed -e "s/:/%3a/g" -e "s:/:%2f:g")"
 
-  echo Working directory is $cache
-  echo Mirror is $mirror
-  mkdir -p "$cache/$mirrordir"
-  cd "$cache/$mirrordir"
+    echo "Working directory is $cache"
+    echo "Mirror is $mirror"
+    mkdir -p "$cache/$mirrordir"
+    cd "$cache/$mirrordir" || return
 }
 
 
 function getsetup()
 {
-#
-  currdir="$(pwd)"
-  if test "$noscripts" == "0"
-  then
-    if test "$invalidate" == "0" && [ -s "$currdir/setup.ini" ] && [ -s "$currdir/setup.ini-save" ] && [ $(find "$currdir" -mtime 0 -type f -regex '.*setup.ini-save' 2>/dev/null) ] && cmp -s "$currdir/setup.ini" "$currdir/setup.ini-save" ; then
-    echo "setup.ini taken from the cache"
-  else
-    touch setup.ini
-    mv setup.ini setup.ini-save
-    wget --user-agent="$USER_AGENT" -N $mirror/$CYGWIN_VERSION/setup.bz2
-    if test -e setup.bz2 && test $? -eq 0
+    currdir="$(pwd)"
+    if test "$noscripts" == "0"
     then
-      bunzip2 setup.bz2
-      mv setup setup.ini
-      echo Updated setup.ini
-    else
-      wget --user-agent="$USER_AGENT" -N $mirror/$CYGWIN_VERSION/setup.ini
-      if test -e setup.ini && test $? -eq 0
-      then
-      echo Updated setup.ini
-      else
-      mv setup.ini-save setup.ini
-      echo Error updating setup.ini, reverting
-      fi
+        if test "$invalidate" == "0" && [ -s "$currdir/setup.ini" ] && [ -s "$currdir/setup.ini-save" ] && [ "$(find "$currdir" -mtime 0 -type f -regex '.*setup.ini-save' 2>/dev/null)" ] && cmp -s "$currdir/setup.ini" "$currdir/setup.ini-save" ; then
+            echo "setup.ini taken from the cache"
+        else
+            touch setup.ini
+            mv setup.ini setup.ini-save
+            wget --user-agent="$USER_AGENT" -N "$mirror/$CYGWIN_VERSION/setup.bz2"
+            if test -e setup.bz2 && test $? -eq 0
+            then
+                bunzip2 setup.bz2
+                mv setup setup.ini
+                echo "Updated setup.ini"
+            else
+                wget --user-agent="$USER_AGENT" -N "$mirror/$CYGWIN_VERSION/setup.ini"
+                if test -e setup.ini && test $? -eq 0
+                then
+                    echo "Updated setup.ini"
+                else
+                    mv setup.ini-save setup.ini
+                    echo "Error updating setup.ini, reverting"
+                fi
+            fi
+        fi
     fi
-  fi
-  fi
 }
 
 
@@ -125,37 +126,40 @@ noscripts=0
 invalidate=0
 file=""
 command=""
-filepackages=""
 packages=""
 force=0
 
 function checkCygwin() {
-  if test "$noscripts" == "0"
-  then
-    # Check if the underlying Cygwin distribution is up to date
-    local newest_cygwin_version=$( get_newest_cygwin_version )
-    if [[ -z "$newest_cygwin_version" ]]; then
-      echo -e "[WARNING] Could not check the Cygwin distribution version. Installed packages may not work!"
-      return
-    else
-      local newest_cygwin_version_number=$( get_version_as_number $newest_cygwin_version )
-      local current_cygwin_version=$( get_current_cygwin_version )
-      local current_cygwin_version_number=$( get_version_as_number $current_cygwin_version )
-      if [[ $newest_cygwin_version_number -gt $current_cygwin_version_number ]]; then
-        if [[ force -eq 1 ]]; then
-            echo -e "CRITICAL: The underlying Cygwin version is outdated! Force option enabled - continuing!"
+    if test "$noscripts" == "0"
+    then
+        # Check if the underlying Cygwin distribution is up to date
+        local newest_cygwin_version
+        newest_cygwin_version=$( get_newest_cygwin_version )
+        if [[ -z "$newest_cygwin_version" ]]; then
+            echo -e "[WARNING] Could not check the Cygwin distribution version. Installed packages may not work!"
+            return
         else
-            echo -e "-------------------------------------------------------------------------------"
-            echo -e "CRITICAL: The underlying Cygwin version is outdated!"
-            echo -e "It's forbidden to install new packages as they may fail to work."
-            echo -e "Execute 'babun update' and follow the instructions to update Cygwin."
-            echo -e "If you know what you are doing add '--force' flag to proceed."
-            echo -e "-------------------------------------------------------------------------------"
-            exit 1
+            local newest_cygwin_version_number
+            newest_cygwin_version_number=$( get_version_as_number "$newest_cygwin_version" )
+            local current_cygwin_version
+            current_cygwin_version=$( get_current_cygwin_version )
+            local current_cygwin_version_number
+            current_cygwin_version_number=$( get_version_as_number "$current_cygwin_version" )
+            if [[ $newest_cygwin_version_number -gt $current_cygwin_version_number ]]; then
+                if [[ force -eq 1 ]]; then
+                    echo -e "CRITICAL: The underlying Cygwin version is outdated! Force option enabled - continuing!"
+                else
+                    echo -e "-------------------------------------------------------------------------------"
+                    echo -e "CRITICAL: The underlying Cygwin version is outdated!"
+                    echo -e "It's forbidden to install new packages as they may fail to work."
+                    echo -e "Execute 'babun update' and follow the instructions to update Cygwin."
+                    echo -e "If you know what you are doing add '--force' flag to proceed."
+                    echo -e "-------------------------------------------------------------------------------"
+                    exit 1
+                fi
+            fi
         fi
-      fi
     fi
-  fi
 }
 
 function installPkg()
@@ -164,35 +168,34 @@ function installPkg()
  for pkg in $packages
     do
 
-    already=`grep -c "^$pkg " /etc/setup/installed.db`
-    if test $already -ge 1
+    already=$(grep -c "^$pkg " /etc/setup/installed.db)
+    if test "$already" -ge 1
     then
-      echo Package $pkg is already installed, skipping
+      echo "Package $pkg is already installed, skipping"
       continue
     fi
     echo ""
-    echo Installing $pkg
+    echo "Installing $pkg"
 
     # look for package and save desc file
 
     mkdir -p "release/$pkg"
     cat setup.ini | awk > "release/$pkg/desc" -v package="$pkg" \
-      'BEGIN{RS="\n\n@ "; FS="\n"} {if ($1 == package) {desc = $0; px++}} \
-       END {if (px == 1 && desc != "") print desc; else print "Package not found"}'
+      'BEGIN{RS="\n\n@ "; FS="\n"} {if ($1 == package) {desc = $0; px++}} END {if (px == 1 && desc != "") print desc; else print "Package not found"}'
 
-    desc=`cat "release/$pkg/desc"`
+    desc=$(cat "release/$pkg/desc")
     if test "-$desc-" = "-Package not found-"
     then
-      echo Package $pkg not found or ambiguous name, exiting
+      echo "Package $pkg not found or ambiguous name, exiting"
       rm -r "release/$pkg"
       exit 1
     fi
-    echo Found package $pkg
+    echo Found package "$pkg"
 
     # download and unpack the bz2 file
 
     # pick the latest version, which comes first
-    install=`cat "release/$pkg/desc" | awk '/^install: / { print $2; exit }'`
+    install=$(cat "release/$pkg/desc" | awk '/^install: / { print $2; exit }')
 
     if test "-$install-" = "--"
     then
@@ -200,20 +203,20 @@ function installPkg()
       exit 1
     fi
 
-    file=`basename $install`
-    cd "release/$pkg"
-    wget --user-agent="$USER_AGENT" -nc $mirror/$install
+    file=$(basename "$install")
+    cd "release/$pkg" || return
+    wget --user-agent="$USER_AGENT" -nc "$mirror/$install"
 
     # check the verification hash (md5 or sha512)
-    digest=`cat "desc" | awk '/^install: / { print $4; exit }'`
-    md5digactual=`md5sum $file | awk '{print $1}'`
-    if ! [[ $digest == $md5digactual ]]
+    digest=$(cat "desc" | awk '/^install: / { print $4; exit }')
+    md5digactual=$(md5sum "$file" | awk '{print $1}')
+    if ! [[ $digest == "$md5digactual" ]]
     then
-      shadigactual=`sha512sum $file | awk '{print $1}'`
-      if ! [[ $digest == $shadigactual ]]
+      shadigactual=$(sha512sum "$file" | awk '{print $1}')
+      if ! [[ $digest == "$shadigactual" ]]
       then
-        echo Verification hash did not match, exiting
-        rm $file # Remove the file with bad checksum
+        echo "Verification hash did not match, exiting"
+        rm "$file" # Remove the file with bad checksum
         exit 1
       fi
     fi
@@ -221,19 +224,18 @@ function installPkg()
     echo "Unpacking..."
     #determine file type
     if [ "${file##*.}" == "xz" ]; then
-      cat $file | tar > "/etc/setup/$pkg.lst" xvJf - -C /
+      cat "$file" | tar > "/etc/setup/$pkg.lst" xvJf - -C /
     else
-      cat $file | bunzip2 | tar > "/etc/setup/$pkg.lst" xvf - -C /
+      cat "$file" | bunzip2 | tar > "/etc/setup/$pkg.lst" xvf - -C /
     fi
     gzip -f "/etc/setup/$pkg.lst"
-    cd ../..
+    cd ../.. || return
 
 
     # update the package database
 
-    cat /etc/setup/installed.db | awk > /tmp/awk.$$ -v pkg="$pkg" -v bz=$file \
-      '{if (ins != 1 && pkg < $1) {print pkg " " bz " 0"; ins=1}; print $0} \
-       END{if (ins != 1) print pkg " " bz " 0"}'
+    cat /etc/setup/installed.db | awk > /tmp/awk.$$ -v pkg="$pkg" -v bz="$file" \
+      '{if (ins != 1 && pkg < $1) {print pkg " " bz " 0"; ins=1}; print $0} END{if (ins != 1) print pkg " " bz " 0"}'
     mv /etc/setup/installed.db /etc/setup/installed.db-save
     mv /tmp/awk.$$ /etc/setup/installed.db
 
@@ -241,22 +243,22 @@ function installPkg()
     # recursively install required packages
 
     echo > /tmp/awk.$$ '/^requires: / {s=gensub("(requires: )?([^ ]+) ?", "\\2 ", "g", $0); print s}'
-    requires=`cat "release/$pkg/desc" | awk -f /tmp/awk.$$`
+    requires=$(cat "release/$pkg/desc" | awk -f /tmp/awk.$$)
 
     warn=0
     if ! test "-$requires-" = "--"
     then
-      echo Package $pkg requires the following packages, installing:
-      echo $requires
+      echo "Package $pkg requires the following packages, installing:"
+      echo "$requires"
       for package in $requires
       do
-        already=`grep -c "^$package " /etc/setup/installed.db`
-        if test $already -ge 1
+        already=$(grep -c "^$package " /etc/setup/installed.db)
+        if test "$already" -ge 1
         then
-          echo Package $package is already installed, skipping
+          echo "Package $package is already installed, skipping"
           continue
         fi
-        pact --noscripts install $package
+        pact --noscripts install "$package"
         if ! test $? = 0 ; then warn=1; fi
       done
     fi
@@ -269,15 +271,16 @@ function installPkg()
 
     if ! test $noscripts -eq 1
     then
-      for script in `find /etc/postinstall/ -name *.sh`
+      mapfile -t pscripts < <(find /etc/postinstall/ -name '*.sh')
+      for script in "${pscripts[@]}"
       do
-        echo Running postinstall script: $script
-        $script
-        mv $script $script.done
+        echo "Running postinstall script: $script"
+        "$script"
+        mv "$script" "$script.done"
       done
     fi
 
-    echo Package $pkg installed
+    echo "Package $pkg installed"
 
     done
 }
@@ -288,10 +291,10 @@ function removePkg()
  for pkg in $packages
     do
 
-    already=`grep -c "^$pkg " /etc/setup/installed.db`
-    if test $already = 0
+    already=$(grep -c "^$pkg " /etc/setup/installed.db)
+    if test "$already" = 0
     then
-      echo Package $pkg is not installed, skipping
+      echo "Package $pkg is not installed, skipping"
       continue
     fi
 
@@ -300,17 +303,17 @@ function removePkg()
     do
       if test "-$pkg-" = "-$req-"
       then
-        echo pact cannot remove package $pkg, exiting
+        echo "pact cannot remove package $pkg, exiting"
         exit 1
       fi
     done
 
     if ! test -e "/etc/setup/$pkg.lst.gz"
     then
-      echo Package manifest missing, cannot remove $pkg.  Exiting
+      echo "Package manifest missing, cannot remove $pkg.  Exiting"
       exit 1
     fi
-    echo Removing $pkg
+    echo "Removing $pkg"
 
     # run preremove scripts
 
@@ -326,7 +329,7 @@ function removePkg()
     cat /etc/setup/installed.db | awk > /tmp/awk.$$ -v pkg="$pkg" '{if (pkg != $1) print $0}'
     mv /etc/setup/installed.db /etc/setup/installed.db-save
     mv /tmp/awk.$$ /etc/setup/installed.db
-    echo Package $pkg removed
+    echo "Package $pkg removed"
 
     done
 }
@@ -417,10 +420,10 @@ case "$command" in
     for pkg in $packages
     do
       echo ""
-      echo Searching for installed packages matching $pkg:
+      echo "Searching for installed packages matching $pkg:"
       awk '/[^ ]+ [^ ]+ 0/ {if ($1 ~ query) print $1}' query="$pkg" /etc/setup/installed.db
       echo ""
-      echo Searching for installable packages matching $pkg:
+      echo "Searching for installable packages matching $pkg:"
       cat setup.ini | awk -v query="$pkg" \
         'BEGIN{RS="\n\n@ "; FS="\n"; ORS="\n"} {if ($1 ~ query) {print $1}}'
     done
@@ -448,19 +451,19 @@ case "$command" in
     checkpackages
     for pkg in $packages
     do
-      key=`which "$pkg" 2>/dev/null | sed "s:^/::"`
+      key=$(which "$pkg" 2>/dev/null | sed "s:^/::")
       if test "-$key-" = "--"
       then
         key="$pkg"
       fi
-      declare -a manifests=($(find /etc/setup -type f -name '*.lst.gz'))
+      mapfile -t manifests < <(find /etc/setup -type f -name '*.lst.gz')
       for manifest in "${manifests[@]}"
       do
-        found=`cat $manifest | gzip -d | grep -o "$key" | wc -l`
-        if test $found -gt 0
+        found=$(cat "$manifest" | gzip -d | grep -o "$key" | wc -l)
+        if test "$found" -gt 0
         then
-          package=`echo $manifest | sed -e "s:/etc/setup/::" -e "s/.lst.gz//"`
-          echo Found $key in the package $package
+          package=$(echo "$manifest" | sed -e "s:/etc/setup/::" -e "s/.lst.gz//")
+          echo "Found $key in the package $package"
         fi
       done
     done
